#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# using flaccid's fork
cookbook 'minidlna',
    :git => 'https://github.com/flaccid/infrastructure.git',
    :path => 'cookbooks/minidlna',
    :ref => 'master'

cookbook 'system',
    :git => 'https://github.com/flaccid/cookbooks.git',
    :path => 'cookbooks/system',
    :ref => 'master'

# http://community.opscode.com/cookbooks/monit
cookbook 'monit',
    :git => 'https://github.com/apsoto/monit.git',
    :ref => 'master'

# ensure the apt cookbook version if compatible with Chef ~= 10
cookbook 'apt',
    :git => 'https://github.com/opscode-cookbooks/apt.git',
    :ref => '1.10.0'